2024-10-01 12:18:21,468 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_UI\GUI_Perform\web_perform_func.py", line 139, in open_interface
    self.pw = post_window()  # 打开接口窗口
              ^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\post_window.py", line 29, in __init__
    self.cb = post_combobox()  # 初始化行数，默认添加一行，初始化选项数据
              ^^^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 31, in __init__
    self.append_line()
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 173, in append_line
    self.append_signal_trigger(self.num)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 121, in append_signal_trigger
    self.control_dict[line]['box_template'].currentIndexChanged.connect(control_groove_locals[i + 'test'])
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'box_template'

2024-10-02 10:02:56,372 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_UI\GUI_Perform\web_perform_func.py", line 139, in open_interface
    self.pw = post_window()  # 打开接口窗口
              ^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\post_window.py", line 29, in __init__
    self.cb = post_combobox()  # 初始化行数，默认添加一行，初始化选项数据
              ^^^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 35, in __init__
    self.append_line()
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 182, in append_line
    self.append_signal_trigger(self.num)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 129, in append_signal_trigger
    self.control_dict[line]['box_file'].currentIndexChanged.connect(self.pf.preview_button_isbool(control_locals_file, control_locals_preview))
TypeError: argument 1 has unexpected type 'NoneType'

2024-10-02 10:02:57,929 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_UI\GUI_Perform\web_perform_func.py", line 139, in open_interface
    self.pw = post_window()  # 打开接口窗口
              ^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\post_window.py", line 29, in __init__
    self.cb = post_combobox()  # 初始化行数，默认添加一行，初始化选项数据
              ^^^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 35, in __init__
    self.append_line()
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 182, in append_line
    self.append_signal_trigger(self.num)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 129, in append_signal_trigger
    self.control_dict[line]['box_file'].currentIndexChanged.connect(self.pf.preview_button_isbool(control_locals_file, control_locals_preview))
TypeError: argument 1 has unexpected type 'NoneType'

2024-10-02 10:10:16,442 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_UI\GUI_Perform\web_perform_func.py", line 139, in open_interface
    self.pw = post_window()  # 打开接口窗口
              ^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\post_window.py", line 29, in __init__
    self.cb = post_combobox()  # 初始化行数，默认添加一行，初始化选项数据
              ^^^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 35, in __init__
    self.append_line()
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 182, in append_line
    self.append_signal_trigger(self.num)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 129, in append_signal_trigger
    self.control_dict[line]['box_file'].currentIndexChanged.connect(self.pf.preview_button_isbool(control_locals_file, control_locals_preview))
TypeError: argument 1 has unexpected type 'NoneType'

2024-10-02 10:13:24,780 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_UI\GUI_Perform\web_perform_func.py", line 139, in open_interface
    self.pw = post_window()  # 打开接口窗口
              ^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\post_window.py", line 29, in __init__
    self.cb = post_combobox()  # 初始化行数，默认添加一行，初始化选项数据
              ^^^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 35, in __init__
    self.append_line()
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 182, in append_line
    self.append_signal_trigger(self.num)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 129, in append_signal_trigger
    self.control_dict[line]['box_file'].currentIndexChanged.connect(self.pf.preview_button_isbool(control_locals_file, control_locals_preview))
TypeError: argument 1 has unexpected type 'NoneType'

2024-10-02 10:18:40,090 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_UI\GUI_Perform\web_perform_func.py", line 139, in open_interface
    self.pw = post_window()  # 打开接口窗口
              ^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\post_window.py", line 29, in __init__
    self.cb = post_combobox()  # 初始化行数，默认添加一行，初始化选项数据
              ^^^^^^^^^^^^^^^
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 35, in __init__
    self.append_line()
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 186, in append_line
    self.append_signal_trigger(self.num)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_ComboBox\post_combobox.py", line 130, in append_signal_trigger
    self.control_dict[line]['box_file'].currentIndexChanged.connect(control_groove_locals)
TypeError: argument 1 has unexpected type 'dict'

2024-10-02 14:37:18,532 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Thread\post_thread.py", line 24, in run
    self.pr.issue_resquest(self.post_combobox)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Request\post_request.py", line 12, in issue_resquest
    print(file_option['bu_file'].currentText())
          ~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'int' object is not subscriptable

2024-10-02 14:39:16,368 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Thread\post_thread.py", line 24, in run
    self.pr.issue_resquest(self.post_combobox)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Request\post_request.py", line 12, in issue_resquest
    print(post_combobox[line]['bu_file'].currentText())
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'bu_file'

2024-10-02 14:48:37,238 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Thread\post_thread.py", line 24, in run
    self.pr.issue_resquest(self.post_combobox)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Request\post_request.py", line 14, in issue_resquest
    next(csv_reader)  #
    ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 70: illegal multibyte sequence

2024-10-02 15:02:57,437 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Template\GIU_Post_Template_File\append_file.py", line 23, in original_file
    self.filedialog(self.listWidget_original)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Template\GIU_Post_Template_File\append_file.py", line 64, in filedialog
    if filename in filename_list:
       ^^^^^^^^
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 1187, in _pydevd_bundle.pydevd_cython_win32_311_64.SafeCallWrapper.__call__
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 627, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 1103, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 1065, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 585, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.do_wait_suspend
  File "C:\Program Files\JetBrains\PyCharm 2024.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1207, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "C:\Program Files\JetBrains\PyCharm 2024.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1222, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt

2024-10-02 16:18:33,431 - web_UI - ERROR - Traceback (most recent call last):
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Template\GIU_Post_Template_File\append_file.py", line 23, in original_file
    self.filedialog(self.listWidget_original)
  File "C:\Users\16946\Desktop\siwu\Auto_wed_current\Auto_Post\GUI_Post_Template\GIU_Post_Template_File\append_file.py", line 63, in filedialog
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 1187, in _pydevd_bundle.pydevd_cython_win32_311_64.SafeCallWrapper.__call__
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 627, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 1103, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 1065, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\\pydevd_cython_win32_311_64.pyx", line 585, in _pydevd_bundle.pydevd_cython_win32_311_64.PyDBFrame.do_wait_suspend
  File "C:\Program Files\JetBrains\PyCharm 2024.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1207, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "C:\Program Files\JetBrains\PyCharm 2024.2.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1222, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt

